# 1. Preproceso

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataframe = pd.read_csv("datosConcatenadossinCI.csv")
dataframe = dataframe.iloc[:,1:]

In [3]:
dataframe = dataframe.drop_duplicates()
dataframe

,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Semestre,Aprobado,...,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,2012,1,2402,COMBUSTION,INT9MECANI,13,1,2012,1,N,...,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_0
1,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,S,...,14,8,0,0,1F-5,0.0,1.0,NaN,NaN,es_1
2,2012,1,2402,COMBUSTION,INT9MECANI,13,1,2012,1,S,...,23,9,0,0,1F-5,0.0,1.0,NaN,NaN,es_2
3,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,S,...,14,8,0,0,"1F-1,2F-2",0.0,1.0,NaN,NaN,es_3
4,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,N,...,4,8,0,0,NaN,0.0,1.0,NaN,NaN,es_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221817,2021,1,5746,PROCESOS DE FABRICACION,MCT9-OPT,13,1,2021,1,N,...,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_3105
221818,2021,1,5746,PROCESOS DE FABRICACION,MCT9-OPT,13,1,2021,1,N,...,26,10,0,0,NaN,0.0,1.0,NaN,NaN,es_2036
221819,2021,1,5746,PROCESOS DE FABRICACION,MCT9-OPT,13,1,2021,1,S,...,26,10,0,0,1F-5,0.0,1.0,NaN,NaN,es_2397
221820,2021,1,5746,PROCESOS DE FABRICACION,MCT9-OPT,13,1,2021,1,N,...,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_2917
221821,2021,1,5746,PROCESOS DE FABRICACION,MCT9-OPT,13,1,2021,1,N,...,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_2504

In [4]:
carreras = ['CGF-PLS13 ','CIV-PLS13 ','ECA-PLS13 ','IND-PLS13 ','MCT-PLS13 ','MEC-PLS13 ','ELE-PLS13 '] 
# solo se considera plan 2013 y cb

In [5]:
fiuna={}
for car in carreras:
    fiuna[car] = dataframe[dataframe['Cod.Car.Sec']==car]

In [6]:
cb = [1,2,3,4] # codigo de cursos de cursos basicos
fiuna_cb={}
for car in carreras:
    fiuna_cb[car] = pd.DataFrame(columns=fiuna[car].columns) # dataframe con los alumnos de cursos basicos 
    for cur in cb:
         fiuna_cb[car] = pd.concat([fiuna_cb[car], fiuna[car][fiuna[car]["Cod.Curso"]==cur]], axis=0)

In [7]:
fiuna_cb['MCT-PLS13 '].head() # carrera MCT, fiuna_cb['CIV-PLS13 '].head() #carrera CIV, ect.

,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Semestre,Aprobado,...,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
15989,2013,1,13005,DIBUJO TECNICO,MCT-PLS13,1,1,2013,1,N,...,0,0,0,0,NaN,0.0,0.0,NaN,NaN,es_1318
22004,2013,2,13001,FISICA 1,MCT-PLS13,1,1,2013,2,S,...,24,0,0,0,1F-3,0.0,0.0,NaN,NaN,es_1514
22012,2013,2,13001,FISICA 1,MCT-PLS13,1,1,2013,2,S,...,24,5,0,0,1F-3,0.0,1.0,NaN,NaN,es_1812
22015,2013,2,13001,FISICA 1,MCT-PLS13,1,1,2013,2,N,...,13,2,30,26,NaN,0.0,1.0,NaN,NaN,es_1815
22027,2013,2,13001,FISICA 1,MCT-PLS13,1,1,2013,2,S,...,17,6,0,0,1F-3,0.0,1.0,NaN,NaN,es_1825

In [8]:
import statistics
def cambiar_nota(a): #funcion que retorna el promedio de las notas finales por cada fila
    notas=[]
    j=""
    for i in a:
        if(j=="-"):
            if(i=="C" or  i=="D"):
                pass
            else:
                notas.append(int(float(i)))
        j=i
    mean = statistics.mean(notas)
    return mean

In [9]:
print("total de alumnos de cb por plan:")
total=0
for car in carreras:
    cant=np.unique(fiuna_cb[car]['id_anony']) #alumnos de cb
    print(car,len(cant)) #cantidad
    total+=len(cant)
print(f"total de alumnos de cb: {total}")

total de alumnos de cb por plan:
CGF-PLS13  381
CIV-PLS13  1887
ECA-PLS13  248
IND-PLS13  553
MCT-PLS13  574
MEC-PLS13  273
ELE-PLS13  1197
total de alumnos de cb: 5113

In [10]:
cb = {}
for car in carreras:
    cb[car] = fiuna_cb[car].copy(deep=True)

In [11]:
for car in carreras: # para cambiar formato de notas finales
    cb[car][['Nota.Final']] = cb[car][['Nota.Final']].fillna('f-0')
    cb[car]['Nota.Final'] =cb[car]['Nota.Final'].apply(cambiar_nota)

In [12]:
cant_materias = []
mate = []
for car in carreras:
    mat = np.unique(cb[car]['Asignatura'])
    cant_materias.append((car,len(mat)))
    lista = np.unique(cb[car][cb[car]['Cod.Curso']==1]['Asignatura']) # Asignaturas de 1er semestre
    mate.append(lista)
    del mat
    del lista
cant_materias # total de materias de cb por plan

[('CGF-PLS13 ', 21),
 ('CIV-PLS13 ', 22),
 ('ECA-PLS13 ', 21),
 ('IND-PLS13 ', 22),
 ('MCT-PLS13 ', 21),
 ('MEC-PLS13 ', 22),
 ('ELE-PLS13 ', 21)]

In [13]:
#print(mate) # materias de 1 semestre de cada plan

In [14]:
materias = mate[0] # Asignaturas de 1er semestre
materias

array(['ALGEBRA LINEAL 1', 'CALCULO 1', 'DIBUJO TECNICO', 'FISICA 1',
       'GEOMETRIA ANALITICA', 'GEOMETRIA DESCRIPTIVA'], dtype=object)

In [15]:
def prom_mat(sem_1, mat): # retorna promedio por materia
    '''param: sem_1 = df de cada alumno
              mat = materia '''
    aux_1 = sem_1[sem_1['Asignatura']==mat]
    aux_2 = aux_1[aux_1['Nota.Final']!=0.0]
    prom = 0
    if len(aux_2)!=0.0:
        prom = sum(aux_2['Nota.Final'])/len(aux_2)
    return prom

def re_s1(sem_1,alum): # recursadas en 1er semestre
    aux_3 = sem_1[sem_1['id_anony']==alum]
    aux_4 = aux_3[aux_3['Aprobado']=='N']
    re = len(aux_4)
    return re

In [21]:
def funcion(df, materias): # retorna df con los features a ser utilizados
    alumnos = np.unique(df['id_anony']) # id de cada alumno
    cant_materias_car = len(np.unique(df['Asignatura'])) #cantidad de materias en cb 
    pasoCB=[] # 1 si ya aprobo CB, 0 si aun no
    tardocb=[] # Cantidad de años que tardo o esta tardando 
    id_alumno=[] #Alumnos
    codcarsec=[] # Codigo de Carrera
    recursadas_s1=[] # recursadas de 1er semestre
    # mate_s1: promedio por materia
    mate_s1={}
    for mat in materias:
        mate_s1[mat]=[]
    promedio_s1=[] #nota promedio del 1er semestre
    for alum in alumnos:
        paso = 0
        r_s1= 0
        pasCB=0
        aux= df[df['id_anony']==alum]
        sem_1 = aux[aux['Cod.Curso']==1]
        for mat in materias:
            mate_s1[mat].append(prom_mat(sem_1, mat))
        r_s1 = re_s1(sem_1,alum)
        sem_1 = sem_1[sem_1['Nota.Final']!=0.0]
        if len(sem_1)!=0.0:
            prom_1 = sum(sem_1['Nota.Final'])/len(sem_1)
        if len(sem_1)==0.0:
            prom_1 = 0
        plan= np.unique(aux['Cod.Car.Sec'])
        aux2= aux[aux['Aprobado']=='S']
        paso= len(np.unique(aux2['Asignatura']))
        tardo = aux['Anho'].max() - aux['danho'].min() #es lo que tardo o esta tardando en pasar
        if paso==cant_materias_car:
            pasCB = 1
        if paso!=cant_materias_car:
            pasCB = 0
        tardocb.append(tardo)
        id_alumno.append(alum)
        codcarsec.append(plan[0])
        pasoCB.append(pasCB)
        recursadas_s1.append(r_s1)
        promedio_s1.append(prom_1)
    
    new = pd.DataFrame({'id_anony':id_alumno,'Cod.Car.Sec':codcarsec,
    'tardoCB':tardocb,'PasoCB':pasoCB,'recursadas_s1':recursadas_s1,
    'prom_al1':mate_s1[materias[0]], 'prom_c1':mate_s1[materias[1]], 'prom_dt':mate_s1[materias[2]],
    'prom_f1':mate_s1[materias[3]], 'prom_ga':mate_s1[materias[4]],'prom_gd':mate_s1[materias[5]],
    'prom_1er_S':promedio_s1 })
    return new

In [22]:
n=0
for car in carreras:
    cb[car] = funcion(cb[car], mate[n])
    n+=1

In [111]:
carreras

['CGF-PLS13 ',
 'CIV-PLS13 ',
 'ECA-PLS13 ',
 'IND-PLS13 ',
 'MCT-PLS13 ',
 'MEC-PLS13 ',
 'ELE-PLS13 ']

In [25]:
n=0
name=['CGF','CIV','ECA','IND','MCT','MEC','ELE']
for car in carreras:
    cb[car][cb[car]['PasoCB']==1].to_csv(f'{name[n]}.csv', index=False)
    n+=1